server:
  port: 2000
  address: localhost

spring:
  h2:
    console:
      enabled: true
  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:testdb
    datasource:
      driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  security:
    jwt:
      keystore-location: "keys/keystore.jks"
      keystore-password: "password"
      key-alias: "alias"